trigger:
  branches:
    include:
      - main

pool:
  name: Default

jobs:
  - deployment: test-deploy
    environment:
      name: sample-environment
    strategy:
     runOnce:
       deploy:
         steps:
           - script: |
               touch file