trigger:
- main

pool:
  name: 'Default'

variables:
  npm_version: "8.5.1"

jobs:
  - job: get_npm_version
    displayName: Get NPM Version

    steps:
      - checkout: main
        displayName: Checkout main branch
      
      - script: |
          echo "##vso[task.setvariable variable=npmVersion;isoutput=true]`npm --version`"
        displayName: Get NPM Version
        name: get_npm_version
  
  - job: get_npm_updates
    dependsOn: get_npm_version
    variables:
      current_npm_version: $[dependencies.get_npm_version.outputs['get_npm_version.npmVersion']]
    condition: ne(variables.current_npm_version, variables.npm_version)

    steps:
      - script: |
          npm update
        displayName: Update NPM
  
  - job: npm_build
    continueOnError: true
    dependsOn: get_npm_updates

    steps:
    - script: |
        mv ./app/* .
      displayName: Move server codes to current directort

    - script: |
        npm i
      displayName: Install modules
    
